services:
  backend:
    build: ./se
    container_name: backend
    restart: always
    env_file:
      - ./se/.env
    ports:
      - "1000:1000"
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./clie
      args:
        VITE_API_UEL: http://13.61.104.200:1000

    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis/redis-stack
    container_name: redis-stack
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
