// This file was generated by Prisma, and assumes you have installed the following: 
// npm install --save-dev prisma dotenv

// Load environment variables from .env
require("dotenv").config();

// Require Prisma defineConfig function
const { defineConfig } = require("prisma/config");

// Export CommonJS configuration
module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
